# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: 
#         - ['localhost:9090']
#         - ['pushgateway:9091']
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus1:9090
      - pushgateway1:9091
